### PR TITLE
Manually apply Python 3.11 migration

### PR DESCRIPTION
**Pull request by chrisburr**
I can't figure out why the bot thinks this isn't solvable so here goes...

### CODE REVIEW

**Comment by chrisburr** [comment]
Ah this is blocked by `pandoc` on `linux-ppc64le`, should this be depending on `nbconvert-core`?

Alternatively we could switch to just `nbconvert-core` for `ppc64le` (or even `ppc64le and py>=311`). (This would also require `notebook` to switch to `nbconvert-core`.)

What do you think @conda-forge/jupyter?

**Comment by xylar** [comment]
I don't feel qualified to say.  @minrk and @ocefpaf, what do you think?

**Comment by ocefpaf** [comment]
> What do you think @conda-forge/jupyter?

I'm OK with those changes. We should've done a while back anyway.

**Comment by xylar** [comment]
This was accomplished in #26

**Pull request closed without merging**
