### PR TITLE
noarch

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing if we can make this noarch.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@minrk do you think it is OK to make this noarch? If so can ou merge this?

**Comment by minrk** [comment]
I don't recall what the noarch issues are anymore. Do executables from noarch packages work properly now?

**Comment by ocefpaf** [comment]
I think so. @msarahan probably knows better.

**Comment by minrk** [comment]
I don't recall what the noarch issues are anymore. Do executables from noarch packages work properly now?

Can you add `jupyter nbextension list` as a test command, to verify that subcommand dispatching works?

**Comment by ocefpaf** [comment]
Both CLI tests are passing on CircleCI:

```
+ jupyter --help
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
  -h, --help     show this help message and exit
  --version      show the jupyter command's version and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json

Available subcommands: bundlerextension console kernel kernelspec migrate
nbconvert nbextension notebook qtconsole run serverextension troubleshoot
trust
+ jupyter nbextension list
      - Validating: OK
Known nbextensions:
  config dir: /feedstock_root/build_artefacts/jupyter_1522154382779/_t_env/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
TEST END: /feedstock_root/build_artefacts/noarch/jupyter-1.0.0-py_1.tar.bz2
INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.
```

What we don't know is if they'll behave as expected on Windows.

**Comment by minrk** [comment]
Ah, good point! I didn't think of the fact that noarch would mean that Windows isn't tested anymore.

I realize now that this is `jupyter` not `jupyter_core`, so it's just an empty metapackage and should be fine.

**Comment by ocefpaf** [comment]
> I realize now that this is `jupyter` not `jupyter_core`

I'm slowly making my way to that package and others :smile:

**Pull request merged**
