### PR TITLE
Make pip package and remove qtconsole for non x86

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@ocefpaf, this is ready.

**Comment by xylar** [comment]
@isuruf and @ocefpaf, it seems this PR undid my work in #8 to convert this to a metapackage.  It's now being installed from source again but, as discussed in #4 and as has re-emerged in #17, this causes conflicts.

Could one of you explain why this was done this way?

**Comment by isuruf** [comment]
This was done to fix #11, where the `jupyter_core` package doesn't have the setuptools metadata for `jupyter` metapackage installed. #18 fixes #17

**Comment by xylar** [comment]
Ah, I see.  Thanks for the details and the fix!

**Pull request merged**
